// <auto-generated />
using System;
using EFCoreMigrationTestWithInheritence_MySql_Updated;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreMigrationTestWithInheritence_MySql_Updated.Migrations
{
    [DbContext(typeof(NewContext))]
    [Migration("20231228013120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shared.Entities.Auths.Auth", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 20, 19, DateTimeKind.Local).AddTicks(4757))
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<string>("LocalIp")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("local_ip");

                    b.Property<uint>("LocalIpPort")
                        .HasMaxLength(5)
                        .HasColumnType("int unsigned")
                        .HasColumnName("local_port");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime")
                        .HasColumnName("logout_time");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpiresIn")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expires_in");

                    b.Property<string>("RemoteIp")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("remote_ip");

                    b.Property<uint>("RemoteIpPort")
                        .HasMaxLength(5)
                        .HasColumnType("int unsigned")
                        .HasColumnName("remote_port");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("token");

                    b.Property<DateTime>("TokenExpiresIn")
                        .HasColumnType("datetime")
                        .HasColumnName("token_expires_in");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("browser_user_agent");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("UserId");

                    b.ToTable("auth", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Chats.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid?>("CreatedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 20, 22, DateTimeKind.Local).AddTicks(6506))
                        .HasColumnName("created_time");

                    b.Property<Guid?>("DeletedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_uuid");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<Guid?>("LastModifiedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by_uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("PictureFileExtension")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("picture_path_file_extension");

                    b.Property<string>("PicturePath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("picture_path");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("CreatedByUserForeignKey");

                    b.HasIndex("DeletedByUserForeignKey");

                    b.HasIndex("LastModifiedByUserForeignKey");

                    b.ToTable("chat", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Chats.ChatRelationToUser", b =>
                {
                    b.Property<Guid>("UserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ChatForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("chat_id");

                    b.Property<Guid?>("CreatedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 20, 33, DateTimeKind.Local).AddTicks(3208))
                        .HasColumnName("created_time");

                    b.Property<Guid?>("DeletedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_uuid");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<Guid?>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<bool?>("IsChatAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin")
                        .HasComment("boolean value to describe if chatmember is chat-admin");

                    b.Property<Guid?>("LastModifiedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by_uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.HasKey("UserForeignKey", "ChatForeignKey");

                    b.HasIndex("ChatForeignKey");

                    b.HasIndex("CreatedByUserForeignKey");

                    b.HasIndex("DeletedByUserForeignKey");

                    b.HasIndex("LastModifiedByUserForeignKey");

                    b.ToTable("chat_relation_to_user", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Chats.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("BinaryContentBase64")
                        .HasColumnType("TEXT")
                        .HasColumnName("binary_content_base64");

                    b.Property<string>("BinaryContentBase64MimeType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("binary_content_base64_mime_type");

                    b.Property<string>("BinaryContentPath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("binary_content_path");

                    b.Property<string>("BinaryContentPathFileExtension")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("binary_content_path_file_extension");

                    b.Property<Guid>("ChatForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("chat_id");

                    b.Property<Guid?>("CreatedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 20, 46, DateTimeKind.Local).AddTicks(632))
                        .HasColumnName("created_time");

                    b.Property<Guid?>("DeletedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_uuid");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<Guid?>("LastModifiedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by_uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<Guid>("UserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ChatForeignKey");

                    b.HasIndex("CreatedByUserForeignKey");

                    b.HasIndex("DeletedByUserForeignKey");

                    b.HasIndex("LastModifiedByUserForeignKey");

                    b.HasIndex("UserForeignKey");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Chats.MessageOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 20, 58, DateTimeKind.Local).AddTicks(2280))
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<Guid>("MessageForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<Guid>("UserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("MessageForeignKey");

                    b.HasIndex("UserForeignKey");

                    b.ToTable("message_outbox", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid?>("CreatedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 20, 11, DateTimeKind.Local).AddTicks(5228))
                        .HasColumnName("created_time");

                    b.Property<Guid?>("DeletedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_uuid");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<Guid?>("LastModifiedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by_uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("CreatedByUserForeignKey");

                    b.HasIndex("DeletedByUserForeignKey");

                    b.HasIndex("LastModifiedByUserForeignKey");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3f357ff-1c85-4e3c-b6b2-21ef4afba71f"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 18, DateTimeKind.Local).AddTicks(3863),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c92db414-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 18, DateTimeKind.Local).AddTicks(3894),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Shared.Entities.Users.EUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid?>("CreatedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 19, 994, DateTimeKind.Local).AddTicks(6035))
                        .HasColumnName("created_time");

                    b.Property<Guid?>("DeletedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_uuid");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<Guid?>("LastModifiedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by_uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("password");

                    b.Property<Guid>("UserTypeForeignKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasDefaultValue(new Guid("c92db314-765b-46dd-bf40-ef7d5a5abd7b"))
                        .HasColumnName("user_type_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("CreatedByUserForeignKey");

                    b.HasIndex("DeletedByUserForeignKey");

                    b.HasIndex("LastModifiedByUserForeignKey");

                    b.HasIndex("UserTypeForeignKey");

                    b.ToTable("e_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8439),
                            Email = "root@localhost",
                            Name = "Root",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("256e2ca9-4ff8-409c-b152-ab09681397e7"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8578),
                            Email = "test0@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8580),
                            Name = "Test0",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("8cb91647-dcd0-41f6-b89b-b9eaf1f8041d"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8596),
                            Email = "test1@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8597),
                            Name = "Test1",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("fad11e86-70eb-4928-836c-e071a2b6c9d0"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8628),
                            Email = "test2@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8629),
                            Name = "Test2",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("a971f50e-50e5-4c33-abe0-b2b4202db5c4"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8633),
                            Email = "test3@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8634),
                            Name = "Test3",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("d12671c9-baca-459a-bb18-38154a5a7787"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8638),
                            Email = "test4@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8639),
                            Name = "Test4",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("d809ae39-d78f-45bd-b0e5-4422c4f03023"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8644),
                            Email = "test5@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8645),
                            Name = "Test5",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("146dfc1f-9ce0-4d56-ba66-ab4736164b0f"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8649),
                            Email = "test6@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8650),
                            Name = "Test6",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("bba6a2f8-0f12-4c56-bf2a-a1a067090f30"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8653),
                            Email = "test7@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8654),
                            Name = "Test7",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("d9536f19-ca2b-446a-a36c-c97631f9b98b"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8657),
                            Email = "test8@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8659),
                            Name = "Test8",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        },
                        new
                        {
                            Id = new Guid("13fbd48a-abd1-4b33-85e4-c879c26ba9f6"),
                            CreatedByUserForeignKey = new Guid("c92db313-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8666),
                            Email = "test9@localhost",
                            LastModifiedTime = new DateTime(2023, 12, 28, 2, 31, 20, 10, DateTimeKind.Local).AddTicks(8667),
                            Name = "Test9",
                            Password = "abcd1234",
                            UserTypeForeignKey = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f")
                        });
                });

            modelBuilder.Entity("Shared.Entities.Users.FriendshipRequest", b =>
                {
                    b.Property<Guid>("RequestUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("requester_id");

                    b.Property<Guid>("TargetUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 19, 983, DateTimeKind.Local).AddTicks(338))
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<Guid?>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<string>("TargetUserRequestMessage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("request_message");

                    b.HasKey("RequestUserForeignKey", "TargetUserForeignKey");

                    b.HasIndex(new[] { "RequestUserForeignKey" }, "IDX_FK_FRIENDSHIPREQUEST_REQUESTERUSER_EUSER");

                    b.HasIndex(new[] { "TargetUserForeignKey" }, "IDX_FK_FRIENDSHIPREQUEST_TARGETUSER_EUSER");

                    b.ToTable("friendship_request", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Users.UserHasRelationToFriend", b =>
                {
                    b.Property<Guid>("UserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("UserFriendForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("friend_id");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 19, 977, DateTimeKind.Local).AddTicks(3040))
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<Guid?>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.HasKey("UserForeignKey", "UserFriendForeignKey");

                    b.HasIndex(new[] { "UserForeignKey" }, "IDX_FK_USERHASRELATIONTOFRIEND_USERFOREIGNKEY_EUSER");

                    b.HasIndex(new[] { "UserFriendForeignKey" }, "IDX_FK_USERHASRELATIONTOFRIEND_USERFRIENDFOREIGNKEY_EUSER");

                    b.ToTable("user_has_relation_to_friend", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Users.UserHasRelationToRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 20, 18, DateTimeKind.Local).AddTicks(8552))
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<Guid>("RoleForeignKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasDefaultValue(new Guid("c92db414-765b-46dd-bf40-ef7d5a5abd7b"))
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleForeignKey" }, "IDX_FK_USERHASRELATIONTOROLE_ROLEFOREIGNKEY_ROLE");

                    b.HasIndex(new[] { "UserForeignKey" }, "IDX_FK_USERHASRELATIONTOROLE_USERFOREIGNKEY_EUSER");

                    b.ToTable("user_has_relation_to_role", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Users.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid?>("CreatedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_uuid");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2023, 12, 28, 2, 31, 19, 967, DateTimeKind.Local).AddTicks(6940))
                        .HasColumnName("created_time");

                    b.Property<Guid?>("DeletedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_uuid");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_time");

                    b.Property<Guid?>("LastModifiedByUserForeignKey")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("modified_by_uuid");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("CreatedByUserForeignKey");

                    b.HasIndex("DeletedByUserForeignKey");

                    b.HasIndex("LastModifiedByUserForeignKey");

                    b.ToTable("user_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c92db314-765b-46dd-bf40-ef7d5a5abd7b"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 19, 976, DateTimeKind.Local).AddTicks(8481),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("c3f257ff-1c85-4e3c-b6b2-21ef4afba71f"),
                            CreatedTime = new DateTime(2023, 12, 28, 2, 31, 19, 976, DateTimeKind.Local).AddTicks(8539),
                            Name = "Root"
                        });
                });

            modelBuilder.Entity("Shared.Entities.Auths.Auth", b =>
                {
                    b.HasOne("Shared.Entities.Users.EUser", "User")
                        .WithMany("Auths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AUTH_USERID_TO_EUSER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Entities.Chats.Chat", b =>
                {
                    b.HasOne("Shared.Entities.Users.EUser", "CreatedByUser")
                        .WithMany("CreatedChats")
                        .HasForeignKey("CreatedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CHAT_CREATEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "DeletedByUser")
                        .WithMany("DeletedChats")
                        .HasForeignKey("DeletedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CHAT_DELETEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "LastModifiedByUser")
                        .WithMany("ModifiedChats")
                        .HasForeignKey("LastModifiedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CHAT_LASTMODIFIEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("Shared.Entities.Chats.ChatRelationToUser", b =>
                {
                    b.HasOne("Shared.Entities.Chats.Chat", "Chat")
                        .WithMany("ChatRelationToUsers")
                        .HasForeignKey("ChatForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHATRELATIONTOUSER_CHATFOREIGNKEY_TO_CHAT");

                    b.HasOne("Shared.Entities.Users.EUser", "CreatedByUser")
                        .WithMany("CreatedChatRelationToUsers")
                        .HasForeignKey("CreatedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CHATRELATIONTOUSER_CREATEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "DeletedByUser")
                        .WithMany("DeletedChatRelationToUsers")
                        .HasForeignKey("DeletedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CHATRELATIONTOUSER_DELETEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "LastModifiedByUser")
                        .WithMany("ModifiedChatRelationToUsers")
                        .HasForeignKey("LastModifiedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CHATRELATIONTOUSER_LASTMODIFIEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "User")
                        .WithMany("ChatRelationToUsers")
                        .HasForeignKey("UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHATRELATIONTOUSER_USERFOREIGNKEY_TO_EUSER");

                    b.Navigation("Chat");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Entities.Chats.Message", b =>
                {
                    b.HasOne("Shared.Entities.Chats.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MESSAGE_CHATFOREIGNKEY_TO_CHAT");

                    b.HasOne("Shared.Entities.Users.EUser", "CreatedByUser")
                        .WithMany("CreatedMessages")
                        .HasForeignKey("CreatedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_MESSAGE_CREATEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "DeletedByUser")
                        .WithMany("DeletedMessages")
                        .HasForeignKey("DeletedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_MESSAGE_DELETEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "LastModifiedByUser")
                        .WithMany("ModifiedMessages")
                        .HasForeignKey("LastModifiedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_MESSAGE_LASTMODIFIEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MESSAGE_USERFOREIGNKEY_TO_EUSER");

                    b.Navigation("Chat");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Entities.Chats.MessageOutbox", b =>
                {
                    b.HasOne("Shared.Entities.Chats.Message", "Message")
                        .WithMany("MessagesInOutbox")
                        .HasForeignKey("MessageForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MESSAGEOUTBOX_MESSAGEFOREIGNKEY_TO_CHAT");

                    b.HasOne("Shared.Entities.Users.EUser", "User")
                        .WithMany("MessagesInOutbox")
                        .HasForeignKey("UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MESSAGEOUTBOX_USERFOREIGNKEY_TO_EUSER");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Entities.Roles.Role", b =>
                {
                    b.HasOne("Shared.Entities.Users.EUser", "CreatedByUser")
                        .WithMany("CreatedRoles")
                        .HasForeignKey("CreatedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ROLE_CREATEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "DeletedByUser")
                        .WithMany("DeletedRoles")
                        .HasForeignKey("DeletedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ROLE_DELETEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "LastModifiedByUser")
                        .WithMany("ModifiedRoles")
                        .HasForeignKey("LastModifiedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ROLE_LASTMODIFIEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("Shared.Entities.Users.EUser", b =>
                {
                    b.HasOne("Shared.Entities.Users.EUser", "CreatedByUser")
                        .WithMany("CreatedEUsers")
                        .HasForeignKey("CreatedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_EUSER_CREATEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "DeletedByUser")
                        .WithMany("DeletedEUsers")
                        .HasForeignKey("DeletedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_EUSER_DELETEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "LastModifiedByUser")
                        .WithMany("ModifiedEUsers")
                        .HasForeignKey("LastModifiedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_EUSER_LASTMODIFIEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EUSER_USERTYPEFOREIGNKEY_TO_USERTYPE");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Shared.Entities.Users.FriendshipRequest", b =>
                {
                    b.HasOne("Shared.Entities.Users.EUser", "RequesterUser")
                        .WithMany("FriendshipRequestsWhereIamRequester")
                        .HasForeignKey("RequestUserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FRIENDSHIPREQUEST_REQUESTUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "TargetUser")
                        .WithMany("FriendshipRequestsWhereIamTarget")
                        .HasForeignKey("TargetUserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FRIENDSHIPREQUEST_TARGETUSERFOREIGNKEY_TO_EUSER");

                    b.Navigation("RequesterUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Shared.Entities.Users.UserHasRelationToFriend", b =>
                {
                    b.HasOne("Shared.Entities.Users.EUser", "User")
                        .WithMany("UserHasRelationToFriendsLeft")
                        .HasForeignKey("UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USERHASRELATIONTOFRIEND_USERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "UserFriend")
                        .WithMany("UserHasRelationToFriendsRight")
                        .HasForeignKey("UserFriendForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USERHASRELATIONTOFRIEND_USERFRIENDFOREIGNKEY_TO_EUSER");

                    b.Navigation("User");

                    b.Navigation("UserFriend");
                });

            modelBuilder.Entity("Shared.Entities.Users.UserHasRelationToRole", b =>
                {
                    b.HasOne("Shared.Entities.Roles.Role", "Role")
                        .WithMany("UserHasRelationToRoles")
                        .HasForeignKey("RoleForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USERHASRELATIONTOROLE_ROLEFOREIGNKEY_TO_ROLE");

                    b.HasOne("Shared.Entities.Users.EUser", "User")
                        .WithMany("UserHasRelationToRoles")
                        .HasForeignKey("UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USERHASRELATIONTOROLE_USERFOREIGNKEY_TO_EUSER");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Entities.Users.UserType", b =>
                {
                    b.HasOne("Shared.Entities.Users.EUser", "CreatedByUser")
                        .WithMany("CreatedUserTypes")
                        .HasForeignKey("CreatedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_USERTYPE_CREATEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "DeletedByUser")
                        .WithMany("DeletedUserTypes")
                        .HasForeignKey("DeletedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_USERTYPE_DELETEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.HasOne("Shared.Entities.Users.EUser", "LastModifiedByUser")
                        .WithMany("ModifiedUserTypes")
                        .HasForeignKey("LastModifiedByUserForeignKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_USERTYPE_LASTMODIFIEDBYUSERFOREIGNKEY_TO_EUSER");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("Shared.Entities.Chats.Chat", b =>
                {
                    b.Navigation("ChatRelationToUsers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Shared.Entities.Chats.Message", b =>
                {
                    b.Navigation("MessagesInOutbox");
                });

            modelBuilder.Entity("Shared.Entities.Roles.Role", b =>
                {
                    b.Navigation("UserHasRelationToRoles");
                });

            modelBuilder.Entity("Shared.Entities.Users.EUser", b =>
                {
                    b.Navigation("Auths");

                    b.Navigation("ChatRelationToUsers");

                    b.Navigation("CreatedChatRelationToUsers");

                    b.Navigation("CreatedChats");

                    b.Navigation("CreatedEUsers");

                    b.Navigation("CreatedMessages");

                    b.Navigation("CreatedRoles");

                    b.Navigation("CreatedUserTypes");

                    b.Navigation("DeletedChatRelationToUsers");

                    b.Navigation("DeletedChats");

                    b.Navigation("DeletedEUsers");

                    b.Navigation("DeletedMessages");

                    b.Navigation("DeletedRoles");

                    b.Navigation("DeletedUserTypes");

                    b.Navigation("FriendshipRequestsWhereIamRequester");

                    b.Navigation("FriendshipRequestsWhereIamTarget");

                    b.Navigation("Messages");

                    b.Navigation("MessagesInOutbox");

                    b.Navigation("ModifiedChatRelationToUsers");

                    b.Navigation("ModifiedChats");

                    b.Navigation("ModifiedEUsers");

                    b.Navigation("ModifiedMessages");

                    b.Navigation("ModifiedRoles");

                    b.Navigation("ModifiedUserTypes");

                    b.Navigation("UserHasRelationToFriendsLeft");

                    b.Navigation("UserHasRelationToFriendsRight");

                    b.Navigation("UserHasRelationToRoles");
                });

            modelBuilder.Entity("Shared.Entities.Users.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
